// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDum00QbTnkMx0zX1cqrNz7E3qlmhLLh1o',
    appId: '1:709276772399:web:25e15740d4a6353a5fbeda',
    messagingSenderId: '709276772399',
    projectId: 'borrowtracker-d7d07',
    authDomain: 'borrowtracker-d7d07.firebaseapp.com',
    storageBucket: 'borrowtracker-d7d07.firebasestorage.app',
    measurementId: 'G-7LN7PPKTNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsqbkImi_iLZnszuppgRCbB6qudHehQcc',
    appId: '1:709276772399:android:9958efe8fef7fe9c5fbeda',
    messagingSenderId: '709276772399',
    projectId: 'borrowtracker-d7d07',
    storageBucket: 'borrowtracker-d7d07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxMBjAYoTs1tMPeW4hkE2d2RN3afBbFO8',
    appId: '1:709276772399:ios:5e77ff2c9b6bb1b65fbeda',
    messagingSenderId: '709276772399',
    projectId: 'borrowtracker-d7d07',
    storageBucket: 'borrowtracker-d7d07.firebasestorage.app',
    iosBundleId: 'com.borrowtracker.borrowTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxMBjAYoTs1tMPeW4hkE2d2RN3afBbFO8',
    appId: '1:709276772399:ios:5e77ff2c9b6bb1b65fbeda',
    messagingSenderId: '709276772399',
    projectId: 'borrowtracker-d7d07',
    storageBucket: 'borrowtracker-d7d07.firebasestorage.app',
    iosBundleId: 'com.borrowtracker.borrowTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDum00QbTnkMx0zX1cqrNz7E3qlmhLLh1o',
    appId: '1:709276772399:web:9ae3eea5db5841c85fbeda',
    messagingSenderId: '709276772399',
    projectId: 'borrowtracker-d7d07',
    authDomain: 'borrowtracker-d7d07.firebaseapp.com',
    storageBucket: 'borrowtracker-d7d07.firebasestorage.app',
    measurementId: 'G-PY0Z8Y4DFL',
  );
}
